default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: snap2_development
test:
  <<: *default
  database: snap2_test

production:
  <<: *default
  database: snap2_production
  username: snap2
  password: <%= ENV['SNAP2_DATABASE_PASSWORD'] %>